// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.2
// source: proto/notification.proto

package notificationpb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Enum sesuai DB
type TypeNotification int32

const (
	TypeNotification_EMAIL    TypeNotification = 0
	TypeNotification_PUSH     TypeNotification = 1
	TypeNotification_SMS      TypeNotification = 2
	TypeNotification_WHATSAPP TypeNotification = 3
)

// Enum value maps for TypeNotification.
var (
	TypeNotification_name = map[int32]string{
		0: "EMAIL",
		1: "PUSH",
		2: "SMS",
		3: "WHATSAPP",
	}
	TypeNotification_value = map[string]int32{
		"EMAIL":    0,
		"PUSH":     1,
		"SMS":      2,
		"WHATSAPP": 3,
	}
)

func (x TypeNotification) Enum() *TypeNotification {
	p := new(TypeNotification)
	*p = x
	return p
}

func (x TypeNotification) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (TypeNotification) Descriptor() protoreflect.EnumDescriptor {
	return file_proto_notification_proto_enumTypes[0].Descriptor()
}

func (TypeNotification) Type() protoreflect.EnumType {
	return &file_proto_notification_proto_enumTypes[0]
}

func (x TypeNotification) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use TypeNotification.Descriptor instead.
func (TypeNotification) EnumDescriptor() ([]byte, []int) {
	return file_proto_notification_proto_rawDescGZIP(), []int{0}
}

// Insert
type InsertNotificationOrderRequest struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	UserId           int64                  `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Type             string                 `protobuf:"bytes,2,opt,name=type,proto3" json:"type,omitempty"`
	TypeNotification TypeNotification       `protobuf:"varint,3,opt,name=type_notification,json=typeNotification,proto3,enum=notification.TypeNotification" json:"type_notification,omitempty"`
	// data template
	Name      string `protobuf:"bytes,4,opt,name=name,proto3" json:"name,omitempty"`
	OrderCode string `protobuf:"bytes,5,opt,name=order_code,json=orderCode,proto3" json:"order_code,omitempty"`
	ExpiredAt string `protobuf:"bytes,6,opt,name=expired_at,json=expiredAt,proto3" json:"expired_at,omitempty"`
	// email target
	Email         string `protobuf:"bytes,7,opt,name=email,proto3" json:"email,omitempty"`
	Service       string `protobuf:"bytes,8,opt,name=service,proto3" json:"service,omitempty"`
	Amount        string `protobuf:"bytes,9,opt,name=amount,proto3" json:"amount,omitempty"`
	PaymentCode   string `protobuf:"bytes,10,opt,name=payment_code,json=paymentCode,proto3" json:"payment_code,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *InsertNotificationOrderRequest) Reset() {
	*x = InsertNotificationOrderRequest{}
	mi := &file_proto_notification_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InsertNotificationOrderRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InsertNotificationOrderRequest) ProtoMessage() {}

func (x *InsertNotificationOrderRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_notification_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InsertNotificationOrderRequest.ProtoReflect.Descriptor instead.
func (*InsertNotificationOrderRequest) Descriptor() ([]byte, []int) {
	return file_proto_notification_proto_rawDescGZIP(), []int{0}
}

func (x *InsertNotificationOrderRequest) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *InsertNotificationOrderRequest) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *InsertNotificationOrderRequest) GetTypeNotification() TypeNotification {
	if x != nil {
		return x.TypeNotification
	}
	return TypeNotification_EMAIL
}

func (x *InsertNotificationOrderRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *InsertNotificationOrderRequest) GetOrderCode() string {
	if x != nil {
		return x.OrderCode
	}
	return ""
}

func (x *InsertNotificationOrderRequest) GetExpiredAt() string {
	if x != nil {
		return x.ExpiredAt
	}
	return ""
}

func (x *InsertNotificationOrderRequest) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *InsertNotificationOrderRequest) GetService() string {
	if x != nil {
		return x.Service
	}
	return ""
}

func (x *InsertNotificationOrderRequest) GetAmount() string {
	if x != nil {
		return x.Amount
	}
	return ""
}

func (x *InsertNotificationOrderRequest) GetPaymentCode() string {
	if x != nil {
		return x.PaymentCode
	}
	return ""
}

type InsertNotificationOrderResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *InsertNotificationOrderResponse) Reset() {
	*x = InsertNotificationOrderResponse{}
	mi := &file_proto_notification_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InsertNotificationOrderResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InsertNotificationOrderResponse) ProtoMessage() {}

func (x *InsertNotificationOrderResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_notification_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InsertNotificationOrderResponse.ProtoReflect.Descriptor instead.
func (*InsertNotificationOrderResponse) Descriptor() ([]byte, []int) {
	return file_proto_notification_proto_rawDescGZIP(), []int{1}
}

func (x *InsertNotificationOrderResponse) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *InsertNotificationOrderResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

// Get by user
type GetNotificationsByUserRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        int64                  `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Limit         int32                  `protobuf:"varint,2,opt,name=limit,proto3" json:"limit,omitempty"`
	Offset        int32                  `protobuf:"varint,3,opt,name=offset,proto3" json:"offset,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetNotificationsByUserRequest) Reset() {
	*x = GetNotificationsByUserRequest{}
	mi := &file_proto_notification_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetNotificationsByUserRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetNotificationsByUserRequest) ProtoMessage() {}

func (x *GetNotificationsByUserRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_notification_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetNotificationsByUserRequest.ProtoReflect.Descriptor instead.
func (*GetNotificationsByUserRequest) Descriptor() ([]byte, []int) {
	return file_proto_notification_proto_rawDescGZIP(), []int{2}
}

func (x *GetNotificationsByUserRequest) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *GetNotificationsByUserRequest) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

func (x *GetNotificationsByUserRequest) GetOffset() int32 {
	if x != nil {
		return x.Offset
	}
	return 0
}

type Notification struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	Id               int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	UserId           int64                  `protobuf:"varint,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Type             string                 `protobuf:"bytes,3,opt,name=type,proto3" json:"type,omitempty"`
	TypeNotification TypeNotification       `protobuf:"varint,4,opt,name=type_notification,json=typeNotification,proto3,enum=notification.TypeNotification" json:"type_notification,omitempty"`
	Subject          string                 `protobuf:"bytes,5,opt,name=subject,proto3" json:"subject,omitempty"`
	Body             string                 `protobuf:"bytes,6,opt,name=body,proto3" json:"body,omitempty"`
	SentAt           string                 `protobuf:"bytes,7,opt,name=sent_at,json=sentAt,proto3" json:"sent_at,omitempty"`
	CreatedAt        string                 `protobuf:"bytes,8,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *Notification) Reset() {
	*x = Notification{}
	mi := &file_proto_notification_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Notification) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Notification) ProtoMessage() {}

func (x *Notification) ProtoReflect() protoreflect.Message {
	mi := &file_proto_notification_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Notification.ProtoReflect.Descriptor instead.
func (*Notification) Descriptor() ([]byte, []int) {
	return file_proto_notification_proto_rawDescGZIP(), []int{3}
}

func (x *Notification) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *Notification) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *Notification) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *Notification) GetTypeNotification() TypeNotification {
	if x != nil {
		return x.TypeNotification
	}
	return TypeNotification_EMAIL
}

func (x *Notification) GetSubject() string {
	if x != nil {
		return x.Subject
	}
	return ""
}

func (x *Notification) GetBody() string {
	if x != nil {
		return x.Body
	}
	return ""
}

func (x *Notification) GetSentAt() string {
	if x != nil {
		return x.SentAt
	}
	return ""
}

func (x *Notification) GetCreatedAt() string {
	if x != nil {
		return x.CreatedAt
	}
	return ""
}

type GetNotificationsByUserResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Notifications []*Notification        `protobuf:"bytes,1,rep,name=notifications,proto3" json:"notifications,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetNotificationsByUserResponse) Reset() {
	*x = GetNotificationsByUserResponse{}
	mi := &file_proto_notification_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetNotificationsByUserResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetNotificationsByUserResponse) ProtoMessage() {}

func (x *GetNotificationsByUserResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_notification_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetNotificationsByUserResponse.ProtoReflect.Descriptor instead.
func (*GetNotificationsByUserResponse) Descriptor() ([]byte, []int) {
	return file_proto_notification_proto_rawDescGZIP(), []int{4}
}

func (x *GetNotificationsByUserResponse) GetNotifications() []*Notification {
	if x != nil {
		return x.Notifications
	}
	return nil
}

var File_proto_notification_proto protoreflect.FileDescriptor

const file_proto_notification_proto_rawDesc = "" +
	"\n" +
	"\x18proto/notification.proto\x12\fnotification\"\xd7\x02\n" +
	"\x1eInsertNotificationOrderRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\x03R\x06userId\x12\x12\n" +
	"\x04type\x18\x02 \x01(\tR\x04type\x12K\n" +
	"\x11type_notification\x18\x03 \x01(\x0e2\x1e.notification.TypeNotificationR\x10typeNotification\x12\x12\n" +
	"\x04name\x18\x04 \x01(\tR\x04name\x12\x1d\n" +
	"\n" +
	"order_code\x18\x05 \x01(\tR\torderCode\x12\x1d\n" +
	"\n" +
	"expired_at\x18\x06 \x01(\tR\texpiredAt\x12\x14\n" +
	"\x05email\x18\a \x01(\tR\x05email\x12\x18\n" +
	"\aservice\x18\b \x01(\tR\aservice\x12\x16\n" +
	"\x06amount\x18\t \x01(\tR\x06amount\x12!\n" +
	"\fpayment_code\x18\n" +
	" \x01(\tR\vpaymentCode\"K\n" +
	"\x1fInsertNotificationOrderResponse\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\"f\n" +
	"\x1dGetNotificationsByUserRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\x03R\x06userId\x12\x14\n" +
	"\x05limit\x18\x02 \x01(\x05R\x05limit\x12\x16\n" +
	"\x06offset\x18\x03 \x01(\x05R\x06offset\"\xfe\x01\n" +
	"\fNotification\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\x03R\x06userId\x12\x12\n" +
	"\x04type\x18\x03 \x01(\tR\x04type\x12K\n" +
	"\x11type_notification\x18\x04 \x01(\x0e2\x1e.notification.TypeNotificationR\x10typeNotification\x12\x18\n" +
	"\asubject\x18\x05 \x01(\tR\asubject\x12\x12\n" +
	"\x04body\x18\x06 \x01(\tR\x04body\x12\x17\n" +
	"\asent_at\x18\a \x01(\tR\x06sentAt\x12\x1d\n" +
	"\n" +
	"created_at\x18\b \x01(\tR\tcreatedAt\"b\n" +
	"\x1eGetNotificationsByUserResponse\x12@\n" +
	"\rnotifications\x18\x01 \x03(\v2\x1a.notification.NotificationR\rnotifications*>\n" +
	"\x10TypeNotification\x12\t\n" +
	"\x05EMAIL\x10\x00\x12\b\n" +
	"\x04PUSH\x10\x01\x12\a\n" +
	"\x03SMS\x10\x02\x12\f\n" +
	"\bWHATSAPP\x10\x032\x82\x02\n" +
	"\x13NotificationService\x12v\n" +
	"\x17InsertNotificationOrder\x12,.notification.InsertNotificationOrderRequest\x1a-.notification.InsertNotificationOrderResponse\x12s\n" +
	"\x16GetNotificationsByUser\x12+.notification.GetNotificationsByUserRequest\x1a,.notification.GetNotificationsByUserResponseB%Z#proto/notificationpb;notificationpbb\x06proto3"

var (
	file_proto_notification_proto_rawDescOnce sync.Once
	file_proto_notification_proto_rawDescData []byte
)

func file_proto_notification_proto_rawDescGZIP() []byte {
	file_proto_notification_proto_rawDescOnce.Do(func() {
		file_proto_notification_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_notification_proto_rawDesc), len(file_proto_notification_proto_rawDesc)))
	})
	return file_proto_notification_proto_rawDescData
}

var file_proto_notification_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_proto_notification_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_proto_notification_proto_goTypes = []any{
	(TypeNotification)(0),                   // 0: notification.TypeNotification
	(*InsertNotificationOrderRequest)(nil),  // 1: notification.InsertNotificationOrderRequest
	(*InsertNotificationOrderResponse)(nil), // 2: notification.InsertNotificationOrderResponse
	(*GetNotificationsByUserRequest)(nil),   // 3: notification.GetNotificationsByUserRequest
	(*Notification)(nil),                    // 4: notification.Notification
	(*GetNotificationsByUserResponse)(nil),  // 5: notification.GetNotificationsByUserResponse
}
var file_proto_notification_proto_depIdxs = []int32{
	0, // 0: notification.InsertNotificationOrderRequest.type_notification:type_name -> notification.TypeNotification
	0, // 1: notification.Notification.type_notification:type_name -> notification.TypeNotification
	4, // 2: notification.GetNotificationsByUserResponse.notifications:type_name -> notification.Notification
	1, // 3: notification.NotificationService.InsertNotificationOrder:input_type -> notification.InsertNotificationOrderRequest
	3, // 4: notification.NotificationService.GetNotificationsByUser:input_type -> notification.GetNotificationsByUserRequest
	2, // 5: notification.NotificationService.InsertNotificationOrder:output_type -> notification.InsertNotificationOrderResponse
	5, // 6: notification.NotificationService.GetNotificationsByUser:output_type -> notification.GetNotificationsByUserResponse
	5, // [5:7] is the sub-list for method output_type
	3, // [3:5] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_proto_notification_proto_init() }
func file_proto_notification_proto_init() {
	if File_proto_notification_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_notification_proto_rawDesc), len(file_proto_notification_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_notification_proto_goTypes,
		DependencyIndexes: file_proto_notification_proto_depIdxs,
		EnumInfos:         file_proto_notification_proto_enumTypes,
		MessageInfos:      file_proto_notification_proto_msgTypes,
	}.Build()
	File_proto_notification_proto = out.File
	file_proto_notification_proto_goTypes = nil
	file_proto_notification_proto_depIdxs = nil
}
