// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.2
// source: proto/order.proto

package orderpb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type OrderStatus int32

const (
	OrderStatus_Unspesified     OrderStatus = 0
	OrderStatus_Created         OrderStatus = 1
	OrderStatus_Waiting_payment OrderStatus = 2
	OrderStatus_Paid            OrderStatus = 3
	OrderStatus_Expired         OrderStatus = 4
	OrderStatus_On_progress     OrderStatus = 5
	OrderStatus_Finished        OrderStatus = 6
	OrderStatus_Completed       OrderStatus = 7
	OrderStatus_Cancelled       OrderStatus = 8
)

// Enum value maps for OrderStatus.
var (
	OrderStatus_name = map[int32]string{
		0: "Unspesified",
		1: "Created",
		2: "Waiting_payment",
		3: "Paid",
		4: "Expired",
		5: "On_progress",
		6: "Finished",
		7: "Completed",
		8: "Cancelled",
	}
	OrderStatus_value = map[string]int32{
		"Unspesified":     0,
		"Created":         1,
		"Waiting_payment": 2,
		"Paid":            3,
		"Expired":         4,
		"On_progress":     5,
		"Finished":        6,
		"Completed":       7,
		"Cancelled":       8,
	}
)

func (x OrderStatus) Enum() *OrderStatus {
	p := new(OrderStatus)
	*p = x
	return p
}

func (x OrderStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (OrderStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_proto_order_proto_enumTypes[0].Descriptor()
}

func (OrderStatus) Type() protoreflect.EnumType {
	return &file_proto_order_proto_enumTypes[0]
}

func (x OrderStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use OrderStatus.Descriptor instead.
func (OrderStatus) EnumDescriptor() ([]byte, []int) {
	return file_proto_order_proto_rawDescGZIP(), []int{0}
}

type GetOrderDetailByIDRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	OrderId       int64                  `protobuf:"varint,1,opt,name=order_id,json=orderId,proto3" json:"order_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetOrderDetailByIDRequest) Reset() {
	*x = GetOrderDetailByIDRequest{}
	mi := &file_proto_order_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetOrderDetailByIDRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetOrderDetailByIDRequest) ProtoMessage() {}

func (x *GetOrderDetailByIDRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_order_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetOrderDetailByIDRequest.ProtoReflect.Descriptor instead.
func (*GetOrderDetailByIDRequest) Descriptor() ([]byte, []int) {
	return file_proto_order_proto_rawDescGZIP(), []int{0}
}

func (x *GetOrderDetailByIDRequest) GetOrderId() int64 {
	if x != nil {
		return x.OrderId
	}
	return 0
}

type GetOrderDetailByCodeRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	OrderCode     string                 `protobuf:"bytes,1,opt,name=order_code,json=orderCode,proto3" json:"order_code,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetOrderDetailByCodeRequest) Reset() {
	*x = GetOrderDetailByCodeRequest{}
	mi := &file_proto_order_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetOrderDetailByCodeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetOrderDetailByCodeRequest) ProtoMessage() {}

func (x *GetOrderDetailByCodeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_order_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetOrderDetailByCodeRequest.ProtoReflect.Descriptor instead.
func (*GetOrderDetailByCodeRequest) Descriptor() ([]byte, []int) {
	return file_proto_order_proto_rawDescGZIP(), []int{1}
}

func (x *GetOrderDetailByCodeRequest) GetOrderCode() string {
	if x != nil {
		return x.OrderCode
	}
	return ""
}

type UpdateOrderStatusRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	OrderCode     string                 `protobuf:"bytes,1,opt,name=order_code,json=orderCode,proto3" json:"order_code,omitempty"`
	Status        OrderStatus            `protobuf:"varint,2,opt,name=status,proto3,enum=order.OrderStatus" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateOrderStatusRequest) Reset() {
	*x = UpdateOrderStatusRequest{}
	mi := &file_proto_order_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateOrderStatusRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateOrderStatusRequest) ProtoMessage() {}

func (x *UpdateOrderStatusRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_order_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateOrderStatusRequest.ProtoReflect.Descriptor instead.
func (*UpdateOrderStatusRequest) Descriptor() ([]byte, []int) {
	return file_proto_order_proto_rawDescGZIP(), []int{2}
}

func (x *UpdateOrderStatusRequest) GetOrderCode() string {
	if x != nil {
		return x.OrderCode
	}
	return ""
}

func (x *UpdateOrderStatusRequest) GetStatus() OrderStatus {
	if x != nil {
		return x.Status
	}
	return OrderStatus_Unspesified
}

type BulkUpdateOrderStatusRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	OrderIds      []int64                `protobuf:"varint,1,rep,packed,name=order_ids,json=orderIds,proto3" json:"order_ids,omitempty"`
	Status        OrderStatus            `protobuf:"varint,2,opt,name=status,proto3,enum=order.OrderStatus" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BulkUpdateOrderStatusRequest) Reset() {
	*x = BulkUpdateOrderStatusRequest{}
	mi := &file_proto_order_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BulkUpdateOrderStatusRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BulkUpdateOrderStatusRequest) ProtoMessage() {}

func (x *BulkUpdateOrderStatusRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_order_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BulkUpdateOrderStatusRequest.ProtoReflect.Descriptor instead.
func (*BulkUpdateOrderStatusRequest) Descriptor() ([]byte, []int) {
	return file_proto_order_proto_rawDescGZIP(), []int{3}
}

func (x *BulkUpdateOrderStatusRequest) GetOrderIds() []int64 {
	if x != nil {
		return x.OrderIds
	}
	return nil
}

func (x *BulkUpdateOrderStatusRequest) GetStatus() OrderStatus {
	if x != nil {
		return x.Status
	}
	return OrderStatus_Unspesified
}

type GetOrderDetailByIDResponse struct {
	state               protoimpl.MessageState `protogen:"open.v1"`
	Id                  int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	UserId              int64                  `protobuf:"varint,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	ServiceId           int64                  `protobuf:"varint,3,opt,name=service_id,json=serviceId,proto3" json:"service_id,omitempty"`
	ServiceNameSnapshot string                 `protobuf:"bytes,4,opt,name=service_name_snapshot,json=serviceNameSnapshot,proto3" json:"service_name_snapshot,omitempty"`
	BasePriceSnapshot   int64                  `protobuf:"varint,5,opt,name=base_price_snapshot,json=basePriceSnapshot,proto3" json:"base_price_snapshot,omitempty"`
	TotalPriceSnapshot  int64                  `protobuf:"varint,6,opt,name=total_price_snapshot,json=totalPriceSnapshot,proto3" json:"total_price_snapshot,omitempty"`
	UserNote            string                 `protobuf:"bytes,7,opt,name=user_note,json=userNote,proto3" json:"user_note,omitempty"`
	Status              OrderStatus            `protobuf:"varint,8,opt,name=status,proto3,enum=order.OrderStatus" json:"status,omitempty"`
	Quantity            int32                  `protobuf:"varint,9,opt,name=quantity,proto3" json:"quantity,omitempty"`
	User                *User                  `protobuf:"bytes,10,opt,name=user,proto3" json:"user,omitempty"`
	OrderCode           *OrderCode             `protobuf:"bytes,11,opt,name=order_code,json=orderCode,proto3" json:"order_code,omitempty"`
	OrderSpecifications []*OrderSpecification  `protobuf:"bytes,12,rep,name=order_specifications,json=orderSpecifications,proto3" json:"order_specifications,omitempty"`
	OrderFile           *OrderFile             `protobuf:"bytes,13,opt,name=order_file,json=orderFile,proto3" json:"order_file,omitempty"`
	unknownFields       protoimpl.UnknownFields
	sizeCache           protoimpl.SizeCache
}

func (x *GetOrderDetailByIDResponse) Reset() {
	*x = GetOrderDetailByIDResponse{}
	mi := &file_proto_order_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetOrderDetailByIDResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetOrderDetailByIDResponse) ProtoMessage() {}

func (x *GetOrderDetailByIDResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_order_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetOrderDetailByIDResponse.ProtoReflect.Descriptor instead.
func (*GetOrderDetailByIDResponse) Descriptor() ([]byte, []int) {
	return file_proto_order_proto_rawDescGZIP(), []int{4}
}

func (x *GetOrderDetailByIDResponse) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *GetOrderDetailByIDResponse) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *GetOrderDetailByIDResponse) GetServiceId() int64 {
	if x != nil {
		return x.ServiceId
	}
	return 0
}

func (x *GetOrderDetailByIDResponse) GetServiceNameSnapshot() string {
	if x != nil {
		return x.ServiceNameSnapshot
	}
	return ""
}

func (x *GetOrderDetailByIDResponse) GetBasePriceSnapshot() int64 {
	if x != nil {
		return x.BasePriceSnapshot
	}
	return 0
}

func (x *GetOrderDetailByIDResponse) GetTotalPriceSnapshot() int64 {
	if x != nil {
		return x.TotalPriceSnapshot
	}
	return 0
}

func (x *GetOrderDetailByIDResponse) GetUserNote() string {
	if x != nil {
		return x.UserNote
	}
	return ""
}

func (x *GetOrderDetailByIDResponse) GetStatus() OrderStatus {
	if x != nil {
		return x.Status
	}
	return OrderStatus_Unspesified
}

func (x *GetOrderDetailByIDResponse) GetQuantity() int32 {
	if x != nil {
		return x.Quantity
	}
	return 0
}

func (x *GetOrderDetailByIDResponse) GetUser() *User {
	if x != nil {
		return x.User
	}
	return nil
}

func (x *GetOrderDetailByIDResponse) GetOrderCode() *OrderCode {
	if x != nil {
		return x.OrderCode
	}
	return nil
}

func (x *GetOrderDetailByIDResponse) GetOrderSpecifications() []*OrderSpecification {
	if x != nil {
		return x.OrderSpecifications
	}
	return nil
}

func (x *GetOrderDetailByIDResponse) GetOrderFile() *OrderFile {
	if x != nil {
		return x.OrderFile
	}
	return nil
}

type GetOrderDetailResponse struct {
	state               protoimpl.MessageState `protogen:"open.v1"`
	Id                  int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	UserId              int64                  `protobuf:"varint,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	ServiceId           int64                  `protobuf:"varint,3,opt,name=service_id,json=serviceId,proto3" json:"service_id,omitempty"`
	ServiceNameSnapshot string                 `protobuf:"bytes,4,opt,name=service_name_snapshot,json=serviceNameSnapshot,proto3" json:"service_name_snapshot,omitempty"`
	BasePriceSnapshot   int64                  `protobuf:"varint,5,opt,name=base_price_snapshot,json=basePriceSnapshot,proto3" json:"base_price_snapshot,omitempty"`
	TotalPriceSnapshot  int64                  `protobuf:"varint,6,opt,name=total_price_snapshot,json=totalPriceSnapshot,proto3" json:"total_price_snapshot,omitempty"`
	UserNote            string                 `protobuf:"bytes,7,opt,name=user_note,json=userNote,proto3" json:"user_note,omitempty"`
	Status              OrderStatus            `protobuf:"varint,8,opt,name=status,proto3,enum=order.OrderStatus" json:"status,omitempty"`
	Quantity            int32                  `protobuf:"varint,9,opt,name=quantity,proto3" json:"quantity,omitempty"`
	User                *User                  `protobuf:"bytes,10,opt,name=user,proto3" json:"user,omitempty"`
	OrderCode           *OrderCode             `protobuf:"bytes,11,opt,name=order_code,json=orderCode,proto3" json:"order_code,omitempty"`
	OrderSpecifications []*OrderSpecification  `protobuf:"bytes,12,rep,name=order_specifications,json=orderSpecifications,proto3" json:"order_specifications,omitempty"`
	OrderFile           *OrderFile             `protobuf:"bytes,13,opt,name=order_file,json=orderFile,proto3" json:"order_file,omitempty"`
	unknownFields       protoimpl.UnknownFields
	sizeCache           protoimpl.SizeCache
}

func (x *GetOrderDetailResponse) Reset() {
	*x = GetOrderDetailResponse{}
	mi := &file_proto_order_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetOrderDetailResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetOrderDetailResponse) ProtoMessage() {}

func (x *GetOrderDetailResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_order_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetOrderDetailResponse.ProtoReflect.Descriptor instead.
func (*GetOrderDetailResponse) Descriptor() ([]byte, []int) {
	return file_proto_order_proto_rawDescGZIP(), []int{5}
}

func (x *GetOrderDetailResponse) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *GetOrderDetailResponse) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *GetOrderDetailResponse) GetServiceId() int64 {
	if x != nil {
		return x.ServiceId
	}
	return 0
}

func (x *GetOrderDetailResponse) GetServiceNameSnapshot() string {
	if x != nil {
		return x.ServiceNameSnapshot
	}
	return ""
}

func (x *GetOrderDetailResponse) GetBasePriceSnapshot() int64 {
	if x != nil {
		return x.BasePriceSnapshot
	}
	return 0
}

func (x *GetOrderDetailResponse) GetTotalPriceSnapshot() int64 {
	if x != nil {
		return x.TotalPriceSnapshot
	}
	return 0
}

func (x *GetOrderDetailResponse) GetUserNote() string {
	if x != nil {
		return x.UserNote
	}
	return ""
}

func (x *GetOrderDetailResponse) GetStatus() OrderStatus {
	if x != nil {
		return x.Status
	}
	return OrderStatus_Unspesified
}

func (x *GetOrderDetailResponse) GetQuantity() int32 {
	if x != nil {
		return x.Quantity
	}
	return 0
}

func (x *GetOrderDetailResponse) GetUser() *User {
	if x != nil {
		return x.User
	}
	return nil
}

func (x *GetOrderDetailResponse) GetOrderCode() *OrderCode {
	if x != nil {
		return x.OrderCode
	}
	return nil
}

func (x *GetOrderDetailResponse) GetOrderSpecifications() []*OrderSpecification {
	if x != nil {
		return x.OrderSpecifications
	}
	return nil
}

func (x *GetOrderDetailResponse) GetOrderFile() *OrderFile {
	if x != nil {
		return x.OrderFile
	}
	return nil
}

type UpdateOrderStatusResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateOrderStatusResponse) Reset() {
	*x = UpdateOrderStatusResponse{}
	mi := &file_proto_order_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateOrderStatusResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateOrderStatusResponse) ProtoMessage() {}

func (x *UpdateOrderStatusResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_order_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateOrderStatusResponse.ProtoReflect.Descriptor instead.
func (*UpdateOrderStatusResponse) Descriptor() ([]byte, []int) {
	return file_proto_order_proto_rawDescGZIP(), []int{6}
}

func (x *UpdateOrderStatusResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

type BulkUpdateOrderStatusResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	TotalUpdated  int64                  `protobuf:"varint,2,opt,name=total_updated,json=totalUpdated,proto3" json:"total_updated,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BulkUpdateOrderStatusResponse) Reset() {
	*x = BulkUpdateOrderStatusResponse{}
	mi := &file_proto_order_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BulkUpdateOrderStatusResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BulkUpdateOrderStatusResponse) ProtoMessage() {}

func (x *BulkUpdateOrderStatusResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_order_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BulkUpdateOrderStatusResponse.ProtoReflect.Descriptor instead.
func (*BulkUpdateOrderStatusResponse) Descriptor() ([]byte, []int) {
	return file_proto_order_proto_rawDescGZIP(), []int{7}
}

func (x *BulkUpdateOrderStatusResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *BulkUpdateOrderStatusResponse) GetTotalUpdated() int64 {
	if x != nil {
		return x.TotalUpdated
	}
	return 0
}

type User struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Email         string                 `protobuf:"bytes,3,opt,name=email,proto3" json:"email,omitempty"`
	Phone         string                 `protobuf:"bytes,4,opt,name=phone,proto3" json:"phone,omitempty"`
	AvatarUrl     string                 `protobuf:"bytes,5,opt,name=avatar_url,json=avatarUrl,proto3" json:"avatar_url,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *User) Reset() {
	*x = User{}
	mi := &file_proto_order_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *User) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*User) ProtoMessage() {}

func (x *User) ProtoReflect() protoreflect.Message {
	mi := &file_proto_order_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use User.ProtoReflect.Descriptor instead.
func (*User) Descriptor() ([]byte, []int) {
	return file_proto_order_proto_rawDescGZIP(), []int{8}
}

func (x *User) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *User) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *User) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *User) GetPhone() string {
	if x != nil {
		return x.Phone
	}
	return ""
}

func (x *User) GetAvatarUrl() string {
	if x != nil {
		return x.AvatarUrl
	}
	return ""
}

type OrderCode struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	OrderId       int64                  `protobuf:"varint,2,opt,name=order_id,json=orderId,proto3" json:"order_id,omitempty"`
	Code          string                 `protobuf:"bytes,3,opt,name=code,proto3" json:"code,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *OrderCode) Reset() {
	*x = OrderCode{}
	mi := &file_proto_order_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OrderCode) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OrderCode) ProtoMessage() {}

func (x *OrderCode) ProtoReflect() protoreflect.Message {
	mi := &file_proto_order_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OrderCode.ProtoReflect.Descriptor instead.
func (*OrderCode) Descriptor() ([]byte, []int) {
	return file_proto_order_proto_rawDescGZIP(), []int{9}
}

func (x *OrderCode) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *OrderCode) GetOrderId() int64 {
	if x != nil {
		return x.OrderId
	}
	return 0
}

func (x *OrderCode) GetCode() string {
	if x != nil {
		return x.Code
	}
	return ""
}

type OrderSpecification struct {
	state                     protoimpl.MessageState `protogen:"open.v1"`
	Id                        int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	OrderId                   int64                  `protobuf:"varint,2,opt,name=order_id,json=orderId,proto3" json:"order_id,omitempty"`
	SpecificationId           int64                  `protobuf:"varint,3,opt,name=specification_id,json=specificationId,proto3" json:"specification_id,omitempty"`
	SpecificationNameSnapshot string                 `protobuf:"bytes,4,opt,name=specification_name_snapshot,json=specificationNameSnapshot,proto3" json:"specification_name_snapshot,omitempty"`
	ValueSnapshot             string                 `protobuf:"bytes,5,opt,name=value_snapshot,json=valueSnapshot,proto3" json:"value_snapshot,omitempty"`
	AdditionalPriceSnapshot   int64                  `protobuf:"varint,6,opt,name=additional_price_snapshot,json=additionalPriceSnapshot,proto3" json:"additional_price_snapshot,omitempty"`
	unknownFields             protoimpl.UnknownFields
	sizeCache                 protoimpl.SizeCache
}

func (x *OrderSpecification) Reset() {
	*x = OrderSpecification{}
	mi := &file_proto_order_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OrderSpecification) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OrderSpecification) ProtoMessage() {}

func (x *OrderSpecification) ProtoReflect() protoreflect.Message {
	mi := &file_proto_order_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OrderSpecification.ProtoReflect.Descriptor instead.
func (*OrderSpecification) Descriptor() ([]byte, []int) {
	return file_proto_order_proto_rawDescGZIP(), []int{10}
}

func (x *OrderSpecification) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *OrderSpecification) GetOrderId() int64 {
	if x != nil {
		return x.OrderId
	}
	return 0
}

func (x *OrderSpecification) GetSpecificationId() int64 {
	if x != nil {
		return x.SpecificationId
	}
	return 0
}

func (x *OrderSpecification) GetSpecificationNameSnapshot() string {
	if x != nil {
		return x.SpecificationNameSnapshot
	}
	return ""
}

func (x *OrderSpecification) GetValueSnapshot() string {
	if x != nil {
		return x.ValueSnapshot
	}
	return ""
}

func (x *OrderSpecification) GetAdditionalPriceSnapshot() int64 {
	if x != nil {
		return x.AdditionalPriceSnapshot
	}
	return 0
}

type OrderFile struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	OrderId       int64                  `protobuf:"varint,2,opt,name=order_id,json=orderId,proto3" json:"order_id,omitempty"`
	FileUrl       string                 `protobuf:"bytes,3,opt,name=file_url,json=fileUrl,proto3" json:"file_url,omitempty"`
	Type          string                 `protobuf:"bytes,4,opt,name=type,proto3" json:"type,omitempty"`
	FileType      string                 `protobuf:"bytes,5,opt,name=file_type,json=fileType,proto3" json:"file_type,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *OrderFile) Reset() {
	*x = OrderFile{}
	mi := &file_proto_order_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OrderFile) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OrderFile) ProtoMessage() {}

func (x *OrderFile) ProtoReflect() protoreflect.Message {
	mi := &file_proto_order_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OrderFile.ProtoReflect.Descriptor instead.
func (*OrderFile) Descriptor() ([]byte, []int) {
	return file_proto_order_proto_rawDescGZIP(), []int{11}
}

func (x *OrderFile) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *OrderFile) GetOrderId() int64 {
	if x != nil {
		return x.OrderId
	}
	return 0
}

func (x *OrderFile) GetFileUrl() string {
	if x != nil {
		return x.FileUrl
	}
	return ""
}

func (x *OrderFile) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *OrderFile) GetFileType() string {
	if x != nil {
		return x.FileType
	}
	return ""
}

var File_proto_order_proto protoreflect.FileDescriptor

const file_proto_order_proto_rawDesc = "" +
	"\n" +
	"\x11proto/order.proto\x12\x05order\"6\n" +
	"\x19GetOrderDetailByIDRequest\x12\x19\n" +
	"\border_id\x18\x01 \x01(\x03R\aorderId\"<\n" +
	"\x1bGetOrderDetailByCodeRequest\x12\x1d\n" +
	"\n" +
	"order_code\x18\x01 \x01(\tR\torderCode\"e\n" +
	"\x18UpdateOrderStatusRequest\x12\x1d\n" +
	"\n" +
	"order_code\x18\x01 \x01(\tR\torderCode\x12*\n" +
	"\x06status\x18\x02 \x01(\x0e2\x12.order.OrderStatusR\x06status\"g\n" +
	"\x1cBulkUpdateOrderStatusRequest\x12\x1b\n" +
	"\torder_ids\x18\x01 \x03(\x03R\borderIds\x12*\n" +
	"\x06status\x18\x02 \x01(\x0e2\x12.order.OrderStatusR\x06status\"\xb0\x04\n" +
	"\x1aGetOrderDetailByIDResponse\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\x03R\x06userId\x12\x1d\n" +
	"\n" +
	"service_id\x18\x03 \x01(\x03R\tserviceId\x122\n" +
	"\x15service_name_snapshot\x18\x04 \x01(\tR\x13serviceNameSnapshot\x12.\n" +
	"\x13base_price_snapshot\x18\x05 \x01(\x03R\x11basePriceSnapshot\x120\n" +
	"\x14total_price_snapshot\x18\x06 \x01(\x03R\x12totalPriceSnapshot\x12\x1b\n" +
	"\tuser_note\x18\a \x01(\tR\buserNote\x12*\n" +
	"\x06status\x18\b \x01(\x0e2\x12.order.OrderStatusR\x06status\x12\x1a\n" +
	"\bquantity\x18\t \x01(\x05R\bquantity\x12\x1f\n" +
	"\x04user\x18\n" +
	" \x01(\v2\v.order.UserR\x04user\x12/\n" +
	"\n" +
	"order_code\x18\v \x01(\v2\x10.order.OrderCodeR\torderCode\x12L\n" +
	"\x14order_specifications\x18\f \x03(\v2\x19.order.OrderSpecificationR\x13orderSpecifications\x12/\n" +
	"\n" +
	"order_file\x18\r \x01(\v2\x10.order.OrderFileR\torderFile\"\xac\x04\n" +
	"\x16GetOrderDetailResponse\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\x03R\x06userId\x12\x1d\n" +
	"\n" +
	"service_id\x18\x03 \x01(\x03R\tserviceId\x122\n" +
	"\x15service_name_snapshot\x18\x04 \x01(\tR\x13serviceNameSnapshot\x12.\n" +
	"\x13base_price_snapshot\x18\x05 \x01(\x03R\x11basePriceSnapshot\x120\n" +
	"\x14total_price_snapshot\x18\x06 \x01(\x03R\x12totalPriceSnapshot\x12\x1b\n" +
	"\tuser_note\x18\a \x01(\tR\buserNote\x12*\n" +
	"\x06status\x18\b \x01(\x0e2\x12.order.OrderStatusR\x06status\x12\x1a\n" +
	"\bquantity\x18\t \x01(\x05R\bquantity\x12\x1f\n" +
	"\x04user\x18\n" +
	" \x01(\v2\v.order.UserR\x04user\x12/\n" +
	"\n" +
	"order_code\x18\v \x01(\v2\x10.order.OrderCodeR\torderCode\x12L\n" +
	"\x14order_specifications\x18\f \x03(\v2\x19.order.OrderSpecificationR\x13orderSpecifications\x12/\n" +
	"\n" +
	"order_file\x18\r \x01(\v2\x10.order.OrderFileR\torderFile\"5\n" +
	"\x19UpdateOrderStatusResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\"^\n" +
	"\x1dBulkUpdateOrderStatusResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12#\n" +
	"\rtotal_updated\x18\x02 \x01(\x03R\ftotalUpdated\"u\n" +
	"\x04User\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x14\n" +
	"\x05email\x18\x03 \x01(\tR\x05email\x12\x14\n" +
	"\x05phone\x18\x04 \x01(\tR\x05phone\x12\x1d\n" +
	"\n" +
	"avatar_url\x18\x05 \x01(\tR\tavatarUrl\"J\n" +
	"\tOrderCode\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x19\n" +
	"\border_id\x18\x02 \x01(\x03R\aorderId\x12\x12\n" +
	"\x04code\x18\x03 \x01(\tR\x04code\"\x8d\x02\n" +
	"\x12OrderSpecification\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x19\n" +
	"\border_id\x18\x02 \x01(\x03R\aorderId\x12)\n" +
	"\x10specification_id\x18\x03 \x01(\x03R\x0fspecificationId\x12>\n" +
	"\x1bspecification_name_snapshot\x18\x04 \x01(\tR\x19specificationNameSnapshot\x12%\n" +
	"\x0evalue_snapshot\x18\x05 \x01(\tR\rvalueSnapshot\x12:\n" +
	"\x19additional_price_snapshot\x18\x06 \x01(\x03R\x17additionalPriceSnapshot\"\x82\x01\n" +
	"\tOrderFile\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x19\n" +
	"\border_id\x18\x02 \x01(\x03R\aorderId\x12\x19\n" +
	"\bfile_url\x18\x03 \x01(\tR\afileUrl\x12\x12\n" +
	"\x04type\x18\x04 \x01(\tR\x04type\x12\x1b\n" +
	"\tfile_type\x18\x05 \x01(\tR\bfileType*\x94\x01\n" +
	"\vOrderStatus\x12\x0f\n" +
	"\vUnspesified\x10\x00\x12\v\n" +
	"\aCreated\x10\x01\x12\x13\n" +
	"\x0fWaiting_payment\x10\x02\x12\b\n" +
	"\x04Paid\x10\x03\x12\v\n" +
	"\aExpired\x10\x04\x12\x0f\n" +
	"\vOn_progress\x10\x05\x12\f\n" +
	"\bFinished\x10\x06\x12\r\n" +
	"\tCompleted\x10\a\x12\r\n" +
	"\tCancelled\x10\b2\x80\x03\n" +
	"\fOrderService\x12Y\n" +
	"\x12GetOrderDetailByID\x12 .order.GetOrderDetailByIDRequest\x1a!.order.GetOrderDetailByIDResponse\x12Y\n" +
	"\x14GetOrderDetailByCode\x12\".order.GetOrderDetailByCodeRequest\x1a\x1d.order.GetOrderDetailResponse\x12V\n" +
	"\x11UpdateOrderStatus\x12\x1f.order.UpdateOrderStatusRequest\x1a .order.UpdateOrderStatusResponse\x12b\n" +
	"\x15BulkUpdateOrderStatus\x12#.order.BulkUpdateOrderStatusRequest\x1a$.order.BulkUpdateOrderStatusResponseB\x17Z\x15proto/orderpb;orderpbb\x06proto3"

var (
	file_proto_order_proto_rawDescOnce sync.Once
	file_proto_order_proto_rawDescData []byte
)

func file_proto_order_proto_rawDescGZIP() []byte {
	file_proto_order_proto_rawDescOnce.Do(func() {
		file_proto_order_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_order_proto_rawDesc), len(file_proto_order_proto_rawDesc)))
	})
	return file_proto_order_proto_rawDescData
}

var file_proto_order_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_proto_order_proto_msgTypes = make([]protoimpl.MessageInfo, 12)
var file_proto_order_proto_goTypes = []any{
	(OrderStatus)(0),                      // 0: order.OrderStatus
	(*GetOrderDetailByIDRequest)(nil),     // 1: order.GetOrderDetailByIDRequest
	(*GetOrderDetailByCodeRequest)(nil),   // 2: order.GetOrderDetailByCodeRequest
	(*UpdateOrderStatusRequest)(nil),      // 3: order.UpdateOrderStatusRequest
	(*BulkUpdateOrderStatusRequest)(nil),  // 4: order.BulkUpdateOrderStatusRequest
	(*GetOrderDetailByIDResponse)(nil),    // 5: order.GetOrderDetailByIDResponse
	(*GetOrderDetailResponse)(nil),        // 6: order.GetOrderDetailResponse
	(*UpdateOrderStatusResponse)(nil),     // 7: order.UpdateOrderStatusResponse
	(*BulkUpdateOrderStatusResponse)(nil), // 8: order.BulkUpdateOrderStatusResponse
	(*User)(nil),                          // 9: order.User
	(*OrderCode)(nil),                     // 10: order.OrderCode
	(*OrderSpecification)(nil),            // 11: order.OrderSpecification
	(*OrderFile)(nil),                     // 12: order.OrderFile
}
var file_proto_order_proto_depIdxs = []int32{
	0,  // 0: order.UpdateOrderStatusRequest.status:type_name -> order.OrderStatus
	0,  // 1: order.BulkUpdateOrderStatusRequest.status:type_name -> order.OrderStatus
	0,  // 2: order.GetOrderDetailByIDResponse.status:type_name -> order.OrderStatus
	9,  // 3: order.GetOrderDetailByIDResponse.user:type_name -> order.User
	10, // 4: order.GetOrderDetailByIDResponse.order_code:type_name -> order.OrderCode
	11, // 5: order.GetOrderDetailByIDResponse.order_specifications:type_name -> order.OrderSpecification
	12, // 6: order.GetOrderDetailByIDResponse.order_file:type_name -> order.OrderFile
	0,  // 7: order.GetOrderDetailResponse.status:type_name -> order.OrderStatus
	9,  // 8: order.GetOrderDetailResponse.user:type_name -> order.User
	10, // 9: order.GetOrderDetailResponse.order_code:type_name -> order.OrderCode
	11, // 10: order.GetOrderDetailResponse.order_specifications:type_name -> order.OrderSpecification
	12, // 11: order.GetOrderDetailResponse.order_file:type_name -> order.OrderFile
	1,  // 12: order.OrderService.GetOrderDetailByID:input_type -> order.GetOrderDetailByIDRequest
	2,  // 13: order.OrderService.GetOrderDetailByCode:input_type -> order.GetOrderDetailByCodeRequest
	3,  // 14: order.OrderService.UpdateOrderStatus:input_type -> order.UpdateOrderStatusRequest
	4,  // 15: order.OrderService.BulkUpdateOrderStatus:input_type -> order.BulkUpdateOrderStatusRequest
	5,  // 16: order.OrderService.GetOrderDetailByID:output_type -> order.GetOrderDetailByIDResponse
	6,  // 17: order.OrderService.GetOrderDetailByCode:output_type -> order.GetOrderDetailResponse
	7,  // 18: order.OrderService.UpdateOrderStatus:output_type -> order.UpdateOrderStatusResponse
	8,  // 19: order.OrderService.BulkUpdateOrderStatus:output_type -> order.BulkUpdateOrderStatusResponse
	16, // [16:20] is the sub-list for method output_type
	12, // [12:16] is the sub-list for method input_type
	12, // [12:12] is the sub-list for extension type_name
	12, // [12:12] is the sub-list for extension extendee
	0,  // [0:12] is the sub-list for field type_name
}

func init() { file_proto_order_proto_init() }
func file_proto_order_proto_init() {
	if File_proto_order_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_order_proto_rawDesc), len(file_proto_order_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   12,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_order_proto_goTypes,
		DependencyIndexes: file_proto_order_proto_depIdxs,
		EnumInfos:         file_proto_order_proto_enumTypes,
		MessageInfos:      file_proto_order_proto_msgTypes,
	}.Build()
	File_proto_order_proto = out.File
	file_proto_order_proto_goTypes = nil
	file_proto_order_proto_depIdxs = nil
}
